In [2]:
#import necessary packages, etc.
from datascience import *
import numpy as np

Problem 1:

In [3]:
#Create an array containing 4 string elements: first name, last name, birth state
#and favorite color
personal_info = make_array("Han", "Zhang", "Alabama", "Blue")
personal_info

array(['Han', 'Zhang', 'Alabama', 'Blue'], dtype='<U7')

In [4]:
#1.a: mkae all elements uppercase
np.char.upper(personal_info)

array(['HAN', 'ZHANG', 'ALABAMA', 'BLUE'], dtype='<U7')

In [5]:
#1.b: count the number of times the letter "a" appears in each element of the array
np.char.count(personal_info, 'a')

array([1, 1, 3, 0])

In [6]:
#Create an array containing every other odd number starting with 1 and ending
#with (and including) 41
oddarray = np.arange(1,47, 4)
oddarray

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

In [9]:
#2.a: find the sum and product of the elements in the array
arraysum = np.sum(oddarray)
arrayprod = np.prod(oddarray)
print('The sum of the elements is '+ str(arraysum) +'.')
print('The product of the elements is '+ str(arrayprod) +'.')

The sum of the elements is 276.
The product of the elements is 616159193.


In [10]:
#2.b: take the nautral log of each element
oddarray = oddarray.astype(float)
np.log(oddarray)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])

2.c Optional: The numpy function np.diff finds the difference between adjacent
elements of an array. Find the SUM of adjacent elements of this array.

In [11]:
first = oddarray[0:len(oddarray)-1]
second = oddarray[1:len(oddarray)]
adjacent_sum = first + second
adjacent_sum

array([ 6., 14., 22., 30., 38., 46., 54., 62., 70., 78., 86.])